"""
Advanced Dense Point Cloud Processing Script.

This module provides a standalone CLI tool for post-processing the dense point clouds
generated by COLMAP. It allows for fine-grained control over cleaning operations
such as noise removal, table/plane segmentation, and cluster extraction.

Usage:
    python process_dense.py --input workspace/dense/fused.ply --output cleaned_model.ply
"""

import argparse
from src.dense_processing import DenseProcessor


def main():
    """
    Main CLI entry point for dense cloud processing.

    Parses command-line arguments and orchestrates the cleaning pipeline
    using the DenseProcessor class.
    """
    parser = argparse.ArgumentParser(
        description="Clean and process dense point cloud reconstruction"
    )

    # Input/Output paths
    parser.add_argument(
        "--input",
        type=str,
        default="workspace/dense/fused.ply",
        help="Path to the input PLY file (usually 'fused.ply' from COLMAP)."
    )
    parser.add_argument(
        "--output",
        type=str,
        default="cleaned_book.ply",
        help="Path where the cleaned PLY file will be saved."
    )

    # Pipeline Control Flags
    parser.add_argument(
        "--no-noise-removal",
        action="store_true",
        help="If set, skips the Statistical Outlier Removal step."
    )
    parser.add_argument(
        "--no-plane-removal",
        action="store_true",
        help="If set, skips the RANSAC plane segmentation (table removal)."
    )
    parser.add_argument(
        "--no-clustering",
        action="store_true",
        help="If set, skips DBSCAN clustering (object isolation)."
    )

    # Visualization Options
    parser.add_argument(
        "--visualize-plane",
        action="store_true",
        help="Enables visual debugging of the plane removal step (Red=Plane, Grey=Object)."
    )
    parser.add_argument(
        "--point-size",
        type=float,
        default=2.0,
        help="Sets the point size for the final Open3D visualization window."
    )

    args = parser.parse_args()

    try:

        print("Dense Point Cloud Processing")

        cleaned_pcd = DenseProcessor.clean_point_cloud_advanced(
            input_path=args.input,
            output_path=args.output,
            remove_noise=not args.no_noise_removal,   # Invert flag logic: args.no_noise -> remove=False
            remove_plane=not args.no_plane_removal,
            extract_cluster=not args.no_clustering,
            compute_normals=True,                     # Always compute normals for better rendering
            visualize_plane=args.visualize_plane
        )

        # Visualize the Final Result
        DenseProcessor.visualize_advanced(
            cleaned_pcd,
            window_name="Cleaned Dense Reconstruction",
            point_size=args.point_size
        )

        print("Processing completed successfully!")

    except FileNotFoundError as e:
        print(f"\nError: {e}")
        print("Make sure you have run the reconstruction first:")
        print("  python main.py --video input_video.mp4")
    except Exception as e:
        print(f"\nError: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()